local h = require("tests.helpers")
local z = require("zen")
local describe, it = h.describe, h.it
local assert_eq, assert_true, assert_false = h.assert_eq, h.assert_true, h.assert_false
local assert_throws = h.assert_throws

describe("z.number()", function()
  it("accepts numbers", function()
    assert_eq(z.number():parse(42), 42)
    assert_eq(z.number():parse(0), 0)
    assert_eq(z.number():parse(-1), -1)
    assert_eq(z.number():parse(3.14), 3.14)
  end)

  it("rejects non-numbers", function()
    assert_false((z.number():safe_parse("42")))
    assert_false((z.number():safe_parse(true)))
    assert_false((z.number():safe_parse({})))
    assert_false((z.number():safe_parse(nil)))
  end)

  it("rejects NaN", function()
    local ok, errs = z.number():safe_parse(0/0)
    assert_false(ok)
    assert_eq(errs[1].code, "invalid_type")
  end)

  it("rejects Infinity by default", function()
    assert_false((z.number():safe_parse(math.huge)))
    assert_false((z.number():safe_parse(-math.huge)))
  end)

  it(":allow_infinity() accepts Infinity", function()
    assert_eq(z.number():allow_infinity():parse(math.huge), math.huge)
    assert_eq(z.number():allow_infinity():parse(-math.huge), -math.huge)
  end)

  it("accepts -0", function()
    local ok, result = z.number():safe_parse(-0)
    assert_true(ok)
    assert_eq(result, 0)
  end)

  it(":min() / :gte() enforce minimum", function()
    assert_eq(z.number():min(5):parse(5), 5)
    assert_eq(z.number():min(5):parse(10), 10)
    local ok, errs = z.number():min(5):safe_parse(4)
    assert_false(ok)
    assert_eq(errs[1].code, "too_small")
    assert_eq(z.number():gte(5):parse(5), 5)
  end)

  it(":max() / :lte() enforce maximum", function()
    assert_eq(z.number():max(10):parse(10), 10)
    local ok, errs = z.number():max(10):safe_parse(11)
    assert_false(ok)
    assert_eq(errs[1].code, "too_big")
    assert_eq(z.number():lte(10):parse(10), 10)
  end)

  it(":gt() strictly greater", function()
    assert_eq(z.number():gt(5):parse(6), 6)
    assert_false((z.number():gt(5):safe_parse(5)))
    assert_false((z.number():gt(5):safe_parse(4)))
  end)

  it(":lt() strictly less", function()
    assert_eq(z.number():lt(10):parse(9), 9)
    assert_false((z.number():lt(10):safe_parse(10)))
  end)

  it(":integer() rejects floats", function()
    assert_eq(z.number():integer():parse(42), 42)
    assert_eq(z.number():integer():parse(0), 0)
    assert_false((z.number():integer():safe_parse(3.14)))
  end)

  it(":integer() rejects infinity even with allow_infinity", function()
    assert_false((z.number():allow_infinity():integer():safe_parse(math.huge)))
  end)

  it(":positive() / :negative() / :nonnegative() / :nonpositive()", function()
    assert_eq(z.number():positive():parse(1), 1)
    assert_false((z.number():positive():safe_parse(0)))
    assert_eq(z.number():negative():parse(-1), -1)
    assert_false((z.number():negative():safe_parse(0)))
    assert_eq(z.number():nonnegative():parse(0), 0)
    assert_false((z.number():nonnegative():safe_parse(-1)))
    assert_eq(z.number():nonpositive():parse(0), 0)
    assert_false((z.number():nonpositive():safe_parse(1)))
  end)

  it(":between() enforces inclusive range", function()
    assert_eq(z.number():between(1, 10):parse(1), 1)
    assert_eq(z.number():between(1, 10):parse(5), 5)
    assert_eq(z.number():between(1, 10):parse(10), 10)
    assert_false((z.number():between(1, 10):safe_parse(0)))
    assert_false((z.number():between(1, 10):safe_parse(11)))
  end)

  it(":multiple_of() / :step() check divisibility", function()
    assert_eq(z.number():multiple_of(5):parse(15), 15)
    assert_eq(z.number():multiple_of(5):parse(0), 0)
    assert_false((z.number():multiple_of(5):safe_parse(13)))
    assert_eq(z.number():step(5):parse(10), 10)
  end)

  it("validates API inputs", function()
    assert_throws(function() z.number():min("bad") end, "expects a number")
    assert_throws(function() z.number():max("bad") end, "expects a number")
    assert_throws(function() z.number():gt("bad") end, "expects a number")
    assert_throws(function() z.number():lt("bad") end, "expects a number")
    assert_throws(function() z.number():between("a", 5) end, "expects numbers")
  end)
end)

describe("z.integer()", function()
  it("is shorthand for z.number():integer()", function()
    assert_eq(z.integer():parse(42), 42)
    assert_false((z.integer():safe_parse(3.14)))
  end)

  it("chains with number validators", function()
    assert_eq(z.integer():min(0):max(100):parse(50), 50)
  end)
end)
